### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by JonJMagee** [JonJMagee/Jon-s-Test-rep#10]
**What**

What is going to be done

**Why/ User Benefit**

Why will be be done and how will it benefit the user

**Who needs to work on this**

Who needs to work on it

**Refinement Tasks**

The standard refinement steps that must be completed
- [ ]  Triage / Ticket Refinement
- [ ]  User need / benefit clarified
- [ ]  Owner (s) identified
- [ ] Tasks / Milestones identified

**Tasks, Actions and Milestones**
Where the specific tasks will be recorded
- [ ] Task 1
- [ ] Task 2 etc
