### ISSUE TITLE
Improve how the people use VS Code

### ISSUE THREAD

**Issue by alinagraham** [JonJMagee/Jon-s-Test-rep#11]
# What #

Investigate some ways to improve how people can use VS Code/ a code editor.  Ideas from collab session were as follows; 
- use VS Code built in task runner
- use the terminal built into VS Code
- Add instructions on how to configure auto-save in VS Code
- Make the instructions specific to VS Code

# Why/User Benefit #

As a new user, I want to understand why I need a separate code editor and why it needs to be installed separately, so that I can download it with confidence

# Who might work on this #

- Developers
- Designers 

# Refinement Tasks #

The standard refinement steps that must be completed
- [ ]  Triage / Ticket Refinement
- [ ]  User need / benefit clarified
- [ ]  Initial Discipline Label applied
- [ ] Tasks / Milestones identified

# Tasks, Actions and Milestones #
- [ ] New ways of using a code editor have been investigated
