### ISSUE TITLE
Add content and detail about creating folders for creating a Prototype

### ISSUE THREAD

**Issue by alinagraham** [JonJMagee/Jon-s-Test-rep#12]

**Comment by alinagraham** [comment]
# What #

Add content about how to create folders on a computer and also to remind users that folders names are case sensitive. 

# Why/ User Benefit #

As a new user, I want to easily create, find and select the right folder, So that I can set my prototype up correctly
As a new user, I want to keep all of my files and folders in the same place, So that I can find them easily
As a new user, I want to be able to quickly access my folders within the Code Editor, so that I can start working on the prototype 

# Who needs to work on this #

Content designer

# Refinement Tasks #

The standard refinement steps that must be completed
- [x]  Triage / Ticket Refinement
- [x]  User need / benefit clarified
- [x]  Owner (s) identified
- [x] Tasks / Milestones identified


# Tasks, Actions and Milestones #
Where the specific tasks will be recorded
- [ ] Review existing guidance
- [ ] Move information re: lower case conventions earlier in the process
- [ ] Make any other suitable changes
