### ISSUE TITLE
Fix the need to refresh the browser

### ISSUE THREAD

**Issue by alinagraham** [JonJMagee/Jon-s-Test-rep#13]

**Comment by alinagraham** [comment]
# What #

Fix the need to refresh the browser and look into instructions on how to configure auto-save in VS Code

# Why/ User Benefit #

As a new user, I want to not have to remember to save the code editor or refresh the browser, so that I do not forget and have to figure out why it is not working

# Who needs to work on this #

- Developers
- Designers

# Refinement Tasks #

The standard refinement steps that must be completed
- [ ]  Triage / Ticket Refinement
- [ ]  User need / benefit clarified
- [ ]  Owner (s) identified
- [ ] Tasks / Milestones identified


# Tasks, Actions and Milestones #
Where the specific tasks will be recorded
- [ ] Investigate ways to auto-save or not have to refresh 
- [ ]
