### ISSUE TITLE
Identify and address common mistakes (within the tutorial) in the most suitable format

### ISSUE THREAD

**Issue by alinagraham** [JonJMagee/Jon-s-Test-rep#14]
# What #

Create a help section with common mistakes (within the tutorial) 

# Why/ User Benefit #

As a new user, I want to understand what I've done wrong
So that I can fix the error myself and without support

# Who needs to work on this #

Content Designer
Developer

# Refinement Tasks #

The standard refinement steps that must be completed
- [x]  Triage / Ticket Refinement
- [x]  User need / benefit clarified
- [x]  Owner (s) identified
- [x] Tasks / Milestones identified

# Tasks, Actions and Milestones #
Where the specific tasks will be recorded
- [ ] Identify common mistakes from Mural board
- [ ] Review support log
- [ ] Collect views of team
- [ ] Communicate common mistakes on the tutorial
