### ISSUE TITLE
Investigate which areas of the tutorial should open a new tab automatically

### ISSUE THREAD

**Issue by alinagraham** [JonJMagee/Jon-s-Test-rep#16]
# What #

Investigate which areas of the tutorial should open a new tab automatically 

# Why/ User Benefit #

As a new user, I want to be able to easily find the 'Manage your Prototype' page so that I can quickly access the service when I need to.
As a new user, I want to fully understand what steps I have taken and what steps still remain, so that I do not miss anything that may cause me an issue later. 

# Who needs to work on this #

Designers

# Refinement Tasks #

The standard refinement steps that must be completed
- [ ]  Triage / Ticket Refinement
- [ ]  User need / benefit clarified
- [ ]  Owner (s) identified
- [ ] Tasks / Milestones identified

# Tasks, Actions and Milestones #
Where the specific tasks will be recorded
- [ ] Audit the tutorial links to decide whether they should open in new tab
- [ ] Basic (team internal) user testing
- [ ] Agree / Complete final changes
