### ISSUE TITLE
Document the difference between npm and npx

### ISSUE THREAD

**Issue by alinagraham** [JonJMagee/Jon-s-Test-rep#18]
# What #

Documentation explaining the difference between npm and npx 

# Why/ User Benefit #

New users are confused by the difference between npx create and npm run.  They thought they were the same thing, and they were being asked to do it again.  

# Who needs to work on this #

Developers
Content Designer

# Refinement Tasks #

The standard refinement steps that must be completed
- [x]  Triage / Ticket Refinement
- [x]  User need / benefit clarified
- [x]  Owner (s) identified
- [x] Tasks / Milestones identified

# Tasks, Actions and Milestones #
Where the specific tasks will be recorded
- [ ] Review current documentation
- [ ] Update contents to clarify the difference
