### ISSUE TITLE
Create consistent style when referencing how to change code

### ISSUE THREAD

**Issue by alinagraham** [JonJMagee/Jon-s-Test-rep#19]
# What #

Create a consistent style for the whole of the tutorial, making sure the instruction style does not change half way through.  Currently the style changed in a number of respects, for example - in the second half it went from just showing them how to do something to telling them and then showing them - code steps etc

# Why/ User Benefit #

As a new user, I want the instructions to remain consistent, so that I learn the flow and can get quicker at following the tutorial

# Who needs to work on this #

Content Designer

# Refinement Tasks #

The standard refinement steps that must be completed
- [x]  Triage / Ticket Refinement
- [x]  User need / benefit clarified
- [x]  Owner (s) identified
- [x] Tasks / Milestones identified

# Tasks, Actions and Milestones #
Where the specific tasks will be recorded
- [ ] Review current tutorials holistically
- [ ] Identify differences
- [ ] Agree better approach
- [ ] Change tutorials to that single agreed approach
- [ ] Basic. user testing light
