### ISSUE TITLE
Backlog Ticket 1 (blocked)

### ISSUE THREAD

**Issue by JonJMagee** [JonJMagee/Jon-s-Test-rep#2]
**What**

We need to improve how we use tickets, take ownership of tasks and ensure that we are making progress. This is an attempt to update the ticket process to ensure this is all done consistently.

This example is a ticket that's gone into the backlog but is blocked so we record that and add tag

**Why**

At the moment tickets are inconsistent - lack detail and, often seem to remain open forever without any tangible progress being made, or with a lack of clarity about what needs to be done, by whom, in what sequence or by when!!!!

**User Benefit**

We will be able to more clearly see why we are doing what we are doing and the benefit to the users. Something not always referenced.

**Who needs to work on this**

Ok, so lets start using people tags in here.. I don't know what happens when people are added

Delivery Manager @JonJMagee
An other @oli-rose28
And @alinagraham

**Refinement Tasks**

- [x] Triage / Ticket Refinement
- [x]  User need / benefit clarifiedTasks / Steps / Milestone agreed
- [x]  Owner (s) identified
- [x]  Tasks / Milestones

**Tasks, Actions and Milestones**

- [x] Make up ticket
- [x]  Add blocker label
- [ ]  Task after blocked
- [ ]  Task etc
- [ ]  Task etc

**Comment by JonJMagee** [comment]
Blocker - need to speak to IT - problem with robots attacking users - needs sorting
